export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const SUCCESS_GET_PRODUCTS = 'SUCCESS_GET_PRODUCTS'
export const ERROR_GET_PRODUCTS = 'ERROR_GET_PRODUCTS'

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'

export const EDIT_PRODUCT_LOADING = 'EDIT_PRODUCT_LOADING'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const GET_ONE_PRODCUT = 'GET_ONE_PRODCUT'
export const GET_ONE_PRODUCT_SUCCESS = 'GET_ONE_PRODUCT_SUCCESS' 
export const GET_ONE_PRODUCT_ERROR = 'GET_ONE_PRODUCT_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'